### ISSUE TITLE
The encoders output is not correct

### ISSUE THREAD

**Issue by Desoky01** [Scheik/md49_base_controller#3]
this the output of the two encoders:

```
header: 
  seq: 66
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: 
encoder_l: 0
encoder_r: -1009681623
encoderbyte1l: 0
encoderbyte2l: 0
encoderbyte3l: 0
encoderbyte4l: 0
encoderbyte1r: 195
encoderbyte2r: 209
encoderbyte3r: 123
encoderbyte4r: 41
```

the output of encoder_l and encoder_r is not correct
